### ISSUE TITLE
Cannot read property 'split' of undefined @hierarchyReporter.js

### ISSUE THREAD

**Issue by chit786** [gkushang/cucumber-html-reporter#117]
*Description*

Below function is throwing me exception when trying to generate a consolidated report from parallel cucumber test executions. Sequential execution works fine.

`var getBaseDir = function (suite) {
    var baseDir = [];
    suite.features.forEach(function (feature) {
        **var uriParts = feature.uri.split(path.sep);**
        if (!baseDir.length) {
            baseDir = uriParts;
        } else {
            for (var i = uriParts.length; i > 0; i--) {
                if ((baseDir.length > i) && (baseDir[i] !== uriParts[i])) {
                    baseDir.length = i;
                }
            }
        }
    });
    return baseDir.join(path.sep);
};`

Framework I am using : Protractor - v5.1.2, cucumber js - 2.3.0

When I debug the     `suite.features
`
Its giving me array length of 12, while there are only 2 features in the folder (and rest of the array values are 'undefined')

Also please note I am not using nested folder structure. 

Only 2 feature files are present in the features folder (and step_definitions are also in the same folder , that is how Cucumber JS generates the folder structure.)

Please assist.
```

 var options = {
            theme: 'bootstrap',
            jsonDir: jsonReportFolder,
            output: htmlReports + '/cucumber_parallel.html',
            reportSuiteAsScenarios: true,
            launchReport: true
        };
```
The result of the `cucumberHtmlReporter.generate(options);` is a `cucumber_parallel.html` file

**Comment by gkushang** [comment]
@chit786 

Which module do you use to run in Parallel?

**Comment by chit786** [comment]
@gkushang thank you for response... But I do not understand what you mean , but here is my protractor config.js

```var chai = require("chai");
var chaiAsPromised = require("chai-as-promised");
chai.use(chaiAsPromised);
const DEFAULT_TIMEOUT = 360000;

exports.config = {
    seleniumAddress: "http://localhost:5555/wd/hub",
    baseUrl: "http://localhost:5516",
    capabilities: {
        browserName: process.env.TEST_BROWSER_NAME || "chrome",
        // screenResolution:"1280x720"
        shardTestFiles: true,
        maxInstances : 2,
    },
    chromeOptions: {
        'extensions': [],
        'args': ['--start-maximized']
    },
    framework: "custom",
    frameworkPath: require.resolve("protractor-cucumber-framework"),
    specs: ["../features/*.feature"],
    resultJsonOutputFile: "./reports/json/protractor/protractor_report.json",
    ignoreUncaughtExceptions: true,
    onPrepare: function() {
        browser.ignoreSynchronization = false;
        rootElement : 'html',
        browser.manage().window().maximize();
        global.expect = chai.expect;
        global.EC = protractor.ExpectedConditions;
        global.ECTO = 4000;
        addLibraries({
            '_': 'lodash',
            fs: 'fs',
            moment: 'moment',
            path: 'path',
            requestPromise: 'request-promise',
            temp: 'temp'
        });
        const dslFiles = [
            '../../../integration/e2e-dsl/src/test/javascript/e2e/protractor/dsl/fixtures.js',
            '../../../integration/e2e-dsl/src/test/javascript/e2e/protractor/dsl/flow.js',
            '../../../integration/e2e-dsl/src/test/javascript/e2e/protractor/dsl/server.js',
            '../../../core/xlr-ui/tests/e2e/karma/dsl/fixtures-ci-builder.js'
         ];
        dslFiles.forEach(file => require(file));

        function addLibraries(libraries) {
            for (const key in libraries) {
                global[key] = require(libraries[key]);
            }
        }
        var $ =  function addJQueryLocator() {
            /* Add By.$() custom locator that uses JQuery selectors to find elements.
             * Always returns an array (without jquery wraps) of elements.
             *
             * Do note that $("my selector") (without By!) is Protractor syntax sugar for "By.css('my selector')"!
             */
            By.addLocator('$', function (selector, rootElm) {
                return jQuery(rootElm || document).find(selector).toArray();
            });
        };
    },
    afterLaunch: function afterLaunch () {

        // var cucumberHtmlReporter = require('cucumber-html-reporter');
        // var report = require("cucumber-html-report");
        // var jsonReportFolder = './reports/json';
        // var htmlReports = process.cwd() + "/reports/html";
        //
        // var cucumberReportOptions = {
        //     source: jsonReportFolder + '/cucumber.html',
        //     dest: jsonReportFolder,
        //     name: "cucumber_parallel.html",
        //     title: "Cucumber Report"
        // };
        //
        // var options = {
        //     theme: 'bootstrap',
        //     jsonDir: jsonReportFolder,
        //     output: htmlReports + '/cucumber_parallel.html',
        //     reportSuiteAsScenarios: true,
        //     launchReport: true
        // };
        // try{
        //     cucumberHtmlReporter.generate(options);
        // }catch(e){
        //     // report
        //     //     .create(cucumberReportOptions)
        //     //     .then(function() {
        //     //         console.log('here');
        //     //         //invoke cucumber-html-report
        //     //         // creating two reports(optional) here, cucumber-html-report gives directory already exists as cucumber-html-reporter already creates the html dir!
        //     //         // suggestion- use either one of the reports based on your needs
        //     //         console.log("cucumber_report.html created successfully!");
        //     //     })
        //     //     // .catch(function(err) {
        //     //     //     if (err) {
        //     //     //         console.error(err);
        //     //     //     }
        //     //     // });
        // }


    },
    cucumberOpts: {
        strict: true,
        format: ["pretty"],
        require: ["../features/step_definitions/*.js", "../support/*.js"],
        //tags: "(@Smoke)"
    }
};```

**Comment by chit786** [comment]
The commented code in afterLaunch is where I am trying to run this code.

**Comment by krbaio3** [comment]
I have the same problem:

```script
TypeError: Cannot read property 'split' of undefined
hierarchyReporter.js:22
    at /home/xxxx/Workspace/bzz/node_modules/cucumber-html-reporter/lib/hierarchyReporter.js:22:36
    at Array.forEach (<anonymous>)
    at Object.getBaseDir (/home/xxxxx/Workspace/bzz/node_modules/cucumber-html-reporter/lib/hierarchyReporter.js:21:20)
    at setStats (/home/xxxx/Workspace/bzz/node_modules/cucumber-html-reporter/lib/reporter.js:182:41)
    at generateReport (/home/xxxx/Workspace/bzz/node_modules/cucumber-html-reporter/lib/reporter.js:393:13)
    at Object.generate (/home/xxxx/Workspace/bzz/node_modules/cucumber-html-reporter/lib/reporter.js:439:9)
    at Object.generateReport [as generate] (/home/xxxx/Workspace/bzz/node_modules/cucumber-html-reporter/index.js:30:21)
    at Object.<anonymous> (/home/xxxx/Workspace/bzz/cucumber/reporter/index.js:19:14)
    at Module._compile (module.js:657:14)
    at Object.Module._extensions..js (module.js:671:10)
```
This are the versions:

"protractor": "^5.3.0",
"cucumber": "^4.0.0",
"protractor-cucumber-framework": "^4.2.0",


regards

**Comment by crisbbbm** [comment]
I have the same problem. I have the problem also when running sequential execution. Any ideas? 

```
TypeError: Cannot read property 'split' of undefined
    at test\node_modules\cucumber-html-reporter\lib\hierarchyReporter.js:22:36
    at Array.forEach (<anonymous>)
    at Object.getBaseDir (test\node_modules\cucumber-html-reporter\lib\hierarchyReporter.js:21:20)
    at setStats (test\node_modules\cucumber-html-reporter\lib\reporter.js:198:41)
    at generateReport (test\node_modules\cucumber-html-reporter\lib\reporter.js:425:13)
    at Object.generate (test\node_modules\cucumber-html-reporter\lib\reporter.js:471:9)
    at Object.generateReport [as generate] (test\node_modules\cucumber-html-reporter\index.js:30:21)
    at onCleanUp (test\eclipse-workspace\project\project\protractor.conf.js:71:18)
    at q_1.Promise (test\AppData\Roaming\npm\node_modules\protractor\built\util.js:46:49)
    at Function.promise (test\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:682:9)
    at Object.runFilenameOrFn_ (test\AppData\Roaming\npm\node_modules\protractor\built\util.js:38:16)
    at Runner.exit_ (test\AppData\Roaming\npm\node_modules\protractor\built\runner.js:35:27)
    at q.then.then.then.then.then.then.then.then.then (test\AppData\Roaming\npm\node_modules\protractor\built\runner.js:437:25)
    at _fulfilled (test\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:834:54)
    at test\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:863:30
    at Promise.promise.promiseDispatch (test\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:796:13)
```

**Comment by pmatsinopoulos** [comment]
Any update on this? I am using latest version of cucumber html reporter and I am getting the same error.

**Comment by spiro79** [comment]
Be aware that protractor generates it's own json report file. That report does not have the uri property for the features object. The json file generated by Cucumber does.

What you need to do is point cucumber-html-reporter to the json file generated by Cucumber.

On your protractor.conf.js set the proper value for the `format` property. For example:

```javascript
// cucumber command line options
  cucumberOpts: {
    require: ['./cucumber/*.js'],  // require step definition files before executing features
    tags: [],                      // <string[]> (expression) only execute the features or scenarios with tags matching the expression
    strict: true,                  // <boolean> fail if there are any undefined or pending steps
    format: ['json:/path/to/store/cucumber/report/files'],            // <string[]> (type[:path]) specify the output format, optionally supply PATH to redirect formatter output (repeatable)
    'dry-run': false,              // <boolean> invoke formatters without executing steps
    compiler: []                   // <string[]> ("extension:module") require files with the given EXTENSION after requiring MODULE (repeatable)
  },
```

Then cucumber-html-reporter `jsonDir` will need to point to the same path as `cucumberOpts.format[json]` points to
