### ISSUE TITLE
Scenarios with Doc Strings make reporter fail when bootstrap theme is used

### ISSUE THREAD

**Issue by kirillonufreinko** [gkushang/cucumber-html-reporter#14]
In case when Doc Strings are used in scenario (see https://cucumber.io/docs/reference#doc-strings) and reporter creates the report with bootstrap theme I see the following failure:
`TypeError: Cannot read property '0' of undefined
    at eval (lodash.templateSources[1]:130:18)
    at arrayEach (C:\work\team-city-build-agent\work\c6436fccfd414f1\maestro-client\node_modules\lodash\lodash.js:484:11)
    at Function.forEach (C:\work\team-city-build-agent\work\c6436fccfd414f1\maestro-client\node_modules\lodash\lodash.js:8843:14)
    at eval (lodash.templateSources[1]:104:4)
    at arrayEach (C:\work\team-city-build-agent\work\c6436fccfd414f1\maestro-client\node_modules\lodash\lodash.js:484:11)
    at Function.forEach (C:\work\team-city-build-agent\work\c6436fccfd414f1\maestro-client\node_modules\lodash\lodash.js:8843:14)
    at eval (lodash.templateSources[1]:60:4)
    at arrayEach (C:\work\team-city-build-agent\work\c6436fccfd414f1\maestro-client\node_modules\lodash\lodash.js:484:11)
    at Function.forEach (C:\work\team-city-build-agent\work\c6436fccfd414f1\maestro-client\node_modules\lodash\lodash.js:8843:14)
    at eval (lodash.templateSources[1]:10:4)`

In debug I see following piece of code failing with "Cannot read property '0' of undefined"

`__p += '\n                                  <tr>\n                                  ';
 var cells = rows[0]["cells"]; ;
__p += '\n                                  ';`

It seems this is the consequence of following structure in report
`          {
            "arguments": [
              {
                "line": 235,
                "content": "...."
              }
            ],
            "keyword": "And ",
`
which is caused by the use of Doc Strings it seems

Could you please check?

**Comment by gkushang** [comment]
@kirillonufreinko - thanks for reporting the issue. I will take a look at it.

**Comment by gkushang** [comment]
@kirillonufreinko published the fix with `v0.2.9`
