### ISSUE TITLE
SyntaxError: Unexpected identifier when running node index.js

### ISSUE THREAD

**Issue by VinceBarresi** [gkushang/cucumber-html-reporter#174]
I'm trying to generate the html report from the json but every time I run `node index.js` I see 

```
16:58 $ node index.js
/Users/barresiv/Workspace/msg-nightwatch-cucumber-framework/index.js:9
    theme = "bootstrap"
    ^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:73:7)
    at createScript (vm.js:245:10)
    at Object.runInThisContext (vm.js:297:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/
```
index.js

```
var reporter = require('cucumber-html-reporter');
 
var options = {
    theme: "bootstrap",
    jsonDir: "out/report/cucumber_report.json",
    output: "out/report/cucumber_report.html",
    name: "msg.com Test Engineering Report",
    launchReport = true
    theme = "bootstrap"
    screenshotsDirectory: 'screenshots/',
    storeScreenshots: true
    reportSuiteAsScenarios: true,
    launchReport: true,
    screenshot
    metadata: {
            // "App Version":"0.3.2",
            // "Test Environment": "STAGING",
            // "Browser": "Chrome  54.0.2840.98",
            // "Platform": "Windows 10",
            // "Parallel": "Scenarios",
            // "Executed": "Remote"
    }
}; 

reporter.generate(options);
```

I'm not sure what I'm missing here. Any help would be greatly appreciated.
my env - 
```
node v10.9.0
"cucumber-html-reporter": "4.0.5",
"nightwatch-api": "2.1.1",
"cucumber": "4.2.1",
```

**Comment by PCreations** [comment]
You have typos here : 
```
launchReport = true
 theme = "bootstrap"
```
It should be 
```
launchReport: true,
theme: "bootstrap",
```

**Comment by gkushang** [comment]
thanks @PCreations for responding to the issue. 

@VinceBarresi Please reopen the issue if not resolved
