### ISSUE TITLE
HTML report not generated with a step fails

### ISSUE THREAD

**Issue by 10kresources** [gkushang/cucumber-html-reporter#179]
I am using cucumber-html-reporter with https://github.com/apickli/apickli
The html report is generated if all test passes.
But if the test fails say I was expecting status code 200, but got 404, in this case the JSON is generated with error message like 

"error_message": "Error: stepContext: \ntestOutput: \n  success:  false\n  expected: 201\n  actual:   200\n  response: \n    statusCode: 200\n    headers: \n      access-control-allow-credentials: true\n      access-control-allow-origin:      *\n      content-type:                     application/json\n      date:                             Sat, 04 May 2019 10:26:10 GMT\n      referrer-policy:                  no-referrer-when-downgrade\n      server:                           nginx\n      x-content-type-options:           nosniff\n      x-frame-options:                  DENY\n      x-xss-protection:                 1; mode=block\n      content-length:                   212\n      connection:                       Close\n    body: \n      \"\"\"\n        {\n          \"args\": {}, \n          \"headers\": {\n            \"Cache-Control\": \"no-cache\", \n            \"Host\": \"httpbin.org\", \n            \"User-Agent\": \"apickli\"\n          }, \n          \"origin\": \"194.193.218.35, 194.193.218.35\", \n          \"url\": \"https://httpbin.org/get\"\n        }\n        \n      \"\"\"\n    at Function.<anonymous> (/Users/~/Documents/~/lightbeam/node_modules/cucumber/lib/user_code_runner.js:107:21)\n    at Generator.throw (<anonymous>)\n    at Generator.tryCatcher (/Users/~/Documents/~/lightbeam/node_modules/bluebird/js/release/util.js:16:23)\n    at PromiseSpawn._promiseRejected (/Users/~/Documents/~/lightbeam/node_modules/bluebird/js/release/generators.js:107:10)\n    at Promise._settlePromise (/Users/~/Documents/~/lightbeam/node_modules/bluebird/js/release/promise.js:576:26)\n    at Promise._settlePromise0 (/Users/~/Documents/~/lightbeam/node_modules/bluebird/js/release/promise.js:614:10)\n    at Promise._settlePromises (/Users/~/Documents/~/lightbeam/node_modules/bluebird/js/release/promise.js:690:18)\n    at _drainQueueStep (/Users/~/Documents/~/lightbeam/node_modules/bluebird/js/release/async.js:138:12)\n    at _drainQueue (/Users/~/Documents/~/lightbeam/node_modules/bluebird/js/release/async.js:131:9)\n    at Async._drainQueues (/Users/~/Documents/~/lightbeam/node_modules/bluebird/js/release/async.js:147:5)\n    at Immediate.Async.drainQueues [as _onImmediate] (/Users/~/Documents/~/lightbeam/node_modules/bluebird/js/release/async.js:17:14)\n    at runCallback (timers.js:705:18)\n    at tryOnImmediate (timers.js:676:5)\n    at processImmediate (timers.js:658:5)"
            
            

But HTML report is not generated. 

Any help as to how this can be fixed will be highly appreciated.

Thanks,
N

**Comment by wangh118** [comment]
I have the same issue.

**Comment by danish-gahlout** [comment]
I am also facing the same issue. When all the test case are passed successfully It generate the HTML report as usual but when any test fails it doesn't generate the report and don't give any specific error details that why it didn't generate the report.

Any help will be appreciated.
