### ISSUE TITLE
Sanitize regex fails saving images: `/` character should be removed

### ISSUE THREAD

**Issue by ncounter** [gkushang/cucumber-html-reporter#180]
### The issue
When the Cucumber `output.json` contains data like the following:
```json
{
  "keyword": "Then ",
  "name": "I should see \"/tmp: sticky, directory\" in the command output",
  "line": 113,
}
```

the `node index.js` command fails with because the `step.name` contains the `/` character that is not removed from the [image name sanitization](https://github.com/gkushang/cucumber-html-reporter/blob/develop/lib/reporter.js#L266) and in the end the file cannot be saved because it looks for an inconsistent `path`.

### The problem VS the expected
Wrong image name path: I_should_see_`/`tmp_sticky_directory_in_the_command_output.png
Correct image name path: I_should_see_tmp_sticky_directory_in_the_command_output.png

### The error
The stack-trace below explain it clearly:
```
fs.js:115
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'I_should_see_/tmp_sticky_directory_in_the_command_output.png'
    at Object.openSync (fs.js:439:3)
    at Object.writeFileSync (fs.js:1190:35)
    at /root/node_modules/cucumber-html-reporter/lib/reporter.js:272:40
    at Array.forEach (<anonymous>)
    at /root/node_modules/cucumber-html-reporter/lib/reporter.js:235:41
    at Array.forEach (<anonymous>)
    at /root/node_modules/cucumber-html-reporter/lib/reporter.js:233:31
    at Array.forEach (<anonymous>)
    at /root/node_modules/cucumber-html-reporter/lib/reporter.js:220:30
    at Array.forEach (<anonymous>)
```

### The question
Is there any relevant reason why the `/` character is kept in the ` /[^a-zA-Z0-9/-]+/g` regex?

### The proposed solution
Sanitize the image name from the `/` character: https://github.com/gkushang/cucumber-html-reporter/pull/181

**Comment by ncounter** [comment]
Fixed in https://github.com/gkushang/cucumber-html-reporter/pull/181
