### ISSUE TITLE
Undefined scenario causes lodash template error

### ISSUE THREAD

**Issue by glitchassassin** [gkushang/cucumber-html-reporter#186]
Some of my Cucumber tests are failing at the Before hook, which results in the `result` property not being set on any of the steps in that scenario.

This causes a problem for the template in `templates/_common/bootstrap.hierarchy/features.html`, which tries to check the step.result.status without checking if the step.result exists. It throws an error like the following:

```
lodash.templateSources[1]:186
 if(!step.hidden || step.image || step.text || step.result.status === 'failed') { ;
                                                           ^

TypeError: Cannot read property 'status' of undefined
    at eval (lodash.templateSources[1]:186:60)
    at arrayEach (C:\Users\jwinsl01\WebstormProjects\abps-integration-tests\node_modules\lodash\lodash.js:516:11)
    at Function.forEach (C:\Users\jwinsl01\WebstormProjects\abps-integration-tests\node_modules\lodash\lodash.js:9342:14
)
    at eval (lodash.templateSources[1]:184:4)
    at arrayEach (C:\Users\jwinsl01\WebstormProjects\abps-integration-tests\node_modules\lodash\lodash.js:516:11)
    at Function.forEach (C:\Users\jwinsl01\WebstormProjects\abps-integration-tests\node_modules\lodash\lodash.js:9342:14
)
    at eval (lodash.templateSources[1]:96:4)
    at arrayEach (C:\Users\jwinsl01\WebstormProjects\abps-integration-tests\node_modules\lodash\lodash.js:516:11)
    at Function.forEach (C:\Users\jwinsl01\WebstormProjects\abps-integration-tests\node_modules\lodash\lodash.js:9342:14
)
    at eval (lodash.templateSources[1]:10:4)
```

I'll submit a pull request with my fix shortly.

**Comment by glitchassassin** [comment]
See pull request #187
