### ISSUE TITLE
Problem with using Azure DevOps task PublishCucumberReport@1

### ISSUE THREAD

**Issue by Ivanox73** [gkushang/cucumber-html-reporter#272]
Hi All;
We have been using the PublishCucumberReport@1 task ( for generating HTML report task uses cucumber-html-reporter) in the Azure DevOps CI/CD pipeline for some time but recently we have this error:

2023-03-16T10:10:40.8993637Z Found 1 matching /opt/vsts_agent/_work/1/a/ThorOutput pattern
2023-03-16T10:10:40.8996583Z Processing /opt/vsts_agent/_work/1/a/ThorOutput/cucumberReport-ita-event-mq-consumer.json
2023-03-16T10:10:40.8999026Z Saving modified report as /opt/vsts_agent/_work/1/a/ThorOutput/cucumberReport-ita-event-mq-consumer.json
2023-03-16T10:10:40.9085180Z [command]/opt/vsts_agent/_work/_tool/node/12.22.12/x64/bin/node script.js
2023-03-16T10:10:41.1381283Z /opt/vsts_agent/_work/_tasks/PublishCucumberReport_83c082c0-5032-11ea-8fab-bbe0f0fcf287/1.0.8/reporter/node_modules/cucumber-html-reporter/lib/jsonDir.js:25
2023-03-16T10:10:41.1385161Z             let retried = basename.split(".")[2] ?? "0";
2023-03-16T10:10:41.1386534Z                                                                     ^
2023-03-16T10:10:41.1387123Z 
2023-03-16T10:10:41.1388854Z SyntaxError: Unexpected token '?'
2023-03-16T10:10:41.1391973Z ##[warning]Error: Failed to run script
2023-03-16T10:10:41.1399775Z     at wrapSafe (internal/modules/cjs/loader.js:915:16)
2023-03-16T10:10:41.1400916Z     at Module._compile (internal/modules/cjs/loader.js:963:27)
2023-03-16T10:10:41.1401902Z     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
2023-03-16T10:10:41.1403275Z     at Module.load (internal/modules/cjs/loader.js:863:32)
2023-03-16T10:10:41.1404228Z     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
2023-03-16T10:10:41.1405147Z     at Module.require (internal/modules/cjs/loader.js:887:19)
2023-03-16T10:10:41.1406650Z     at require (internal/modules/cjs/helpers.js:74:18)
2023-03-16T10:10:41.1408458Z     at Object.<anonymous> (/opt/vsts_agent/_work/_tasks/PublishCucumberReport_83c082c0-5032-11ea-8fab-bbe0f0fcf287/1.0.8/reporter/node_modules/cucumber-html-reporter/lib/reporter.js:7:17)
2023-03-16T10:10:41.1409636Z     at Module._compile (internal/modules/cjs/loader.js:999:30)
2023-03-16T10:10:41.1410995Z     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
2023-03-16T10:10:41.1428712Z ##[section]Finishing: Publish Cucumebr Report

We use the task passing a folder where the cucumber report file is present:

**cucumberReport-ita-event-mq-consumer.json**

which is syntactically valid.

The filename used has been the same for some time, but now we have this error

Someone can help us ? Thanks!

**Comment by MGana** [comment]
See Here: https://github.com/gkushang/cucumber-html-reporter/issues/271

**Comment by Ivanox73** [comment]
Thanks!

**Comment by Ivanox73** [comment]
With new version pushed (1.0.9) all works fine! Thanks!
