### ISSUE TITLE
Report is not generated when there are screenshots in steps containing slashes

### ISSUE THREAD

**Issue by AlexandrosD** [gkushang/cucumber-html-reporter#47]
An error occurs when attempting to generate a report that has a screenshot in a step that contains slashes, e.g. like **I should see attachment with filename 'blahblah.txt' having mimetype 'text/plain'**

```
Error: { Error: ENOENT: no such file or directory, open 'c:\project\e2e\reports\screenshot\I_should_see_attachment_with_filename_'blahblah.txt'_having_mimetype_'text\plain'_446.png'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.writeFileSync (fs.js:1333:33)
    at c:\project\node_modules\cucumber-html-reporter\lib\reporter.js:120:36
    at Array.forEach (native)
    at c:\project\node_modules\cucumber-html-reporter\lib\reporter.js:106:41
    at Array.forEach (native)
    at c:\project\node_modules\cucumber-html-reporter\lib\reporter.js:103:31
    at Array.forEach (native)
    at c:\project\node_modules\cucumber-html-reporter\lib\reporter.js:95:30
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'c:\\project\\e2e\\reports\\screenshot\\I_should_see_attachment_with_filename_\'blahblah.txt\'_having_mimetype_\'text\\plain\'_446.png' }
```

Probably this is not escaped or not escaped correctly.

**Comment by AlexandrosD** [comment]
@gkushang I'll look into this more thoroughly and submit a PR

**Comment by AlexandrosD** [comment]
Actually this is fixed in https://github.com/gkushang/cucumber-html-reporter/pull/46/commits/7a40477dd79598073e57181a3b8a3e5723f5ea23 - Closing this issue
