### ISSUE TITLE
error while creating the reports

### ISSUE THREAD

**Issue by pawankums** [gkushang/cucumber-html-reporter#82]
@gkushang hi Kushang, i tried to convert the json file of my cucumber execution to the html report using the JS function given by you. But getting the below error

here, reportConvert.js contains the JS function. 

psingh:debug psingh$ node reportConvert.js
No package.json file found in: package.json, using default name and version.
/Users/psingh/node_modules/cucumber-html-reporter/lib/hierarchyReporter.js:21
    suite.features.forEach(function (feature) {
                   ^

TypeError: suite.features.forEach is not a function
    at Object.getBaseDir (/Users/psingh/node_modules/cucumber-html-reporter/lib/hierarchyReporter.js:21:20)
    at setStats (/Users/psingh/node_modules/cucumber-html-reporter/lib/reporter.js:162:41)
    at generateReport (/Users/psingh/node_modules/cucumber-html-reporter/lib/reporter.js:354:13)
    at Object.generate (/Users/psingh/node_modules/cucumber-html-reporter/lib/reporter.js:399:9)
    at Object.generateReport [as generate] (/Users/psingh/node_modules/cucumber-html-reporter/index.js:30:21)
    at Object.<anonymous> (/Users/psingh/Documents/repos/inventory.truetarget-android/true_target/TrueTarget/build/spoon/debug/reportConvert.js:18:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)

**Comment by vhugogarcia** [comment]
Hello @pawankums were you able to solve the issue? if yes, how?

**Comment by pawankums** [comment]
@vhugogarcia no i could not solve this issue.

**Comment by PavanGurramQA** [comment]
I'm also facing the same issue. Any solution, please? Thanks.

**Comment by pnk125** [comment]
same error getting in my code, did someone found fix for this issue ?

**Comment by vhugogarcia** [comment]
I remember, I fixed this issue while ago. The issue was a special character missed somehow while creating the report and then after changing that it worked. I don't recall exactly where I changed due to I got in-depth changing a lot of things trying to make it work that I ended without knowing where the special character was.

**Comment by SimitTomar** [comment]
Getting the same error with v4.0.0 and 5.0.0, did anyone find a fix for this issue. Seems like a Blocking issue.

**Comment by Bakanych** [comment]
having same

**Comment by Philyorkshire** [comment]
Same here... Seems v6 of cucumber has changed the output format a lot. https://github.com/gkushang/cucumber-html-reporter/issues/202
