### ISSUE TITLE
 CucumberHtmlReport is not a constructor

### ISSUE THREAD

**Issue by edgarechm** [gkushang/cucumber-html-reporter#86]
This is my hooks.js file.

```
var JsonFormatter = require('cucumber').JsonFormatter;
var fs = require('fs');
var reporter = require('cucumber-html-reporter');
var CucumberHtmlReport = require('cucumber-html-report');
var seleniumWebdriver = require('selenium-webdriver');
var {defineSupportCode} = require('cucumber');
var outputDir = './'
	
'use strict';

defineSupportCode(function({After,registerListener}) {

	After(function (scenario,callback) {
		let self = this;
        if (scenario.isFailed()) {
            browser.takeScreenshot().then(function (base64png) {
            	 self.attach(new Buffer(base64png, 'base64'), 'image/png');
                 callback();
            }, function (err) {
                return callback(err);
            });
        } else{
        	callback();
        }
    });

    var createHtmlReport = function (sourceJson) {
        var report = new CucumberHtmlReport({
            source: sourceJson
            , dest: outputDir
        });
        report.createReport();
    };
    
    jsonFormatter = new JsonFormatter;
    jsonFormatter.log = function (string) {
        if (!fs.existsSync(outputDir)) {
            fs.mkdirSync(outputDir);
        }
        
        var targetJson = outputDir + 'cucumber.json';
        fs.writeFile(targetJson, string, function (err) {
            if (err) {
                console.log('Failed to save cucumber test results to json file.');
                console.log(err);
            } else {
                createHtmlReport(targetJson);
            }
        });
    };
    
    registerListener(jsonFormatter);
});
```

When I execute my scripts, at the end of all, it is expected that reporter will grab json file and create report. Instead I get this error message:
```

[14:37:25] E/launcher - CucumberHtmlReport is not a constructor
[14:37:25] E/launcher - TypeError: CucumberHtmlReport is not a constructor
    at createHtmlReport (C:\workspace\support\hooks.js:41:22)
    at C:\workspace\support\hooks.js:60:17
    at C:\workspace\node_modules\graceful-fs\graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:111:15)
[14:37:25] E/launcher - Process exited with error code 199
npm ERR! Test failed.  See above for more details.
```

This issue is similar to this [one](https://github.com/igniteram/protractor-cucumber-allure/issues/8), but couldn't fix doing the same (patching with old version).

**Comment by gkushang** [comment]
Yeah, it is not a constructor but instead exports a function called `generate`. 

You can try replacing, 

```
var createHtmlReport = function (sourceJson) {
        var report = new CucumberHtmlReport({
            source: sourceJson
            , dest: outputDir
        });
        report.createReport();
    };
    
```

with,

```
var createHtmlReport = function (sourceJson) {

    var options = {
        theme: 'bootstrap',
        jsonFile: sourceJson, //please double check, this should be a path to your JSON File
        output: outputDir, //please double check, this should have a file name at the end
        reportSuiteAsScenarios: true,
        launchReport: true
    };

    CucumberHtmlReport.generate(options);
};
    
```

For more [info](https://github.com/gkushang/cucumber-html-reporter). Let us know if you have any further questions.

**Comment by gkushang** [comment]
I see you'r using `cucumber-html-report` but not this module, `cucumber-html-reporter`. The above recommendation was for the later one. 

You'd need to import `var CucumberHtmlReport = require('cucumber-html-reporter');`

**Comment by edgarechm** [comment]
.... Ok, but and now:

```
[15:08:48] E/launcher - CucumberHtmlReport.generate is not a function
[15:08:48] E/launcher - TypeError: CucumberHtmlReport.generate is not a function
    at createHtmlReport (C:\workspace\hooks.js:59:25)
    at C:\workspace\hooks.js:76:17
    at C:\workspace\node_modules\graceful-fs\graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:111:15)
[15:08:48] E/launcher - Process exited with error code 199
npm ERR! Test failed.  See above for more details.

```

**Comment by gkushang** [comment]
Did you import `var CucumberHtmlReport = require('cucumber-html-reporter');` instead of `var CucumberHtmlReport = require('cucumber-html-report'); ` ?

**Comment by gkushang** [comment]
I see. You already have `reporter` required. Without modifying, can you try with this,

```

var createHtmlReport = function (sourceJson) {

    var options = {
        theme: 'bootstrap',
        jsonFile: sourceJson, //please double check, this should be a path to your JSON File
        output: outputDir, //please double check, this should have a file name at the end
        reportSuiteAsScenarios: true,
        launchReport: true
    };

   reporter.generate(options);
};
  
```

**Comment by edgarechm** [comment]
Ok, Thanks. That fixed it. Plus I have to tell at the output, the name of the target html file:

```
var createHtmlReport = function (sourceJson) {

	    var options = {
	        theme: 'bootstrap',
	        jsonFile: sourceJson, //please double check, this should be a path to your JSON File
	        output: outputDir+'index.html', //please double check, this should have a file name at the end
	        reportSuiteAsScenarios: true,
	        launchReport: true
	    };

	   reporter.generate(options);
	};
```
